version: '3'
services:
  server:
    build:
      context: ../..
    volumes:
      - rubygems_cache:/usr/local/bundle
    environment:
      RAILS_ENV: production
      UNICORN_PORT: 3000
      SECRET_KEY_BASE: dheydhgsjryf763723hfnhqwgsgcdtye5241ghdasdfkjghj2138f8cje
      RAILS_SERVE_STATIC_FILES: 'true'
    ports:
      - "${PORT}:3000"
volumes:
  rubygems_cache: