version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app/

  cucumber-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec parallel_cucumber features

  rspec-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec parallel_rspec spec
